hydra:
  job:
    chdir: False

train:
  dataset_name: "music" # huggingface dataset
  seq_len: 1048576
  batch_size: 1
  num_workers: 4
  lr: 3e-4
  weight_decay: 0.01
  num_epochs: 100
  device: "cuda"
  precision: "16-mixed" # not implemented yet
  overfit_single_batch: False

paths:
  save_ckpt_dir: "checkpoints" # directory where checkpoints will be saved
  load_ckpt_path: null # if not None, specifies path to model state dict which will be loaded
  log_dir: "logs"
  hf_repo_id: null # repo id to upload model to huggingface if null model is not uploaded

logger:
  run_name: run-${now:%Y-%m-%d-%H-%M}
  log_every_n_steps: 50
