hydra:
  job:
    chdir: False

train:
  dataset_name: "music" # huggingface dataset
  seq_len: 1048576
  batch_size: 2
  num_workers: 4
  lr: 3e-4
  weight_decay: 0.01
  num_epochs: 100
  device: "cuda"
  precision: "16-mixed" # not implemented yet
  overfit_single_batch: False

var:
  latent_size: 72
  cond_size: 128
  hidden_size: 256
  out_size: 1024
  scales: [1, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048]
  num_spatial_layers: 12
  num_depth_layers: 8
  num_heads: 16
  mlp_ratio: 4.0
  num_codebooks: 9

paths:
  save_ckpt_dir: "checkpoints" # directory where checkpoints will be saved
  load_ckpt_path: null # if not None, specifies path to model state dict which will be loaded
  log_dir: "logs"
  hf_repo_id: null # repo id to upload model to huggingface if null model is not uploaded

logger:
  run_name: run-${now:%Y-%m-%d-%H-%M}
  log_every_n_steps: 50
